namespace Strikers.Core;

public static partial class Library
{
    private static IReadOnlyList<BoardDesign> AllBoards()
    {
        return
        [
            new("Lost terraces", Normal, 3,
            [
                "........",
                ".mmmmmm.",
                "........",
                "........",
                ".mmmmmmm",
                "........",
                "........",
                ".mmmmmm.",
            ]),
            new("Golden aisles", Normal, 3,
            [
                "f..f....",
                "f..f..f.",
                "f..f..f.",
                ".f..f..f",
                ".f..f..f",
                "....f..f",
            ]),
            new("Morass perimeter", Normal, 3,
            [
                "......",
                ".mmmm.",
                ".m..m.",
                ".m..m.",
                ".mmmm.",
                "......",
            ]),
            new("Downland quarters", Normal, 2,
            [
                "...h..",
                "...h..",
                ".h.h..",
                "hhhh..",
                "..hhhh",
                "..h.h.",
                "..h...",
                "..h...",
            ]),
            new("Silent greenwood", Normal, 2,
            [
                "....ff",
                "...ff.",
                "..ff..",
                ".ff...",
                "...ff.",
                "..ff..",
                ".ff...",
                "ff....",
            ]),
            new("Swale split", Normal, 3,
            [
                "mmm.....",
                "..m.....",
                "mmmm....",
                "....mmmm",
                "....m.m.",
                "......mm",
                ".....m.m",
            ]),
            new("Sump spread", Normal, 3,
            [
                "mmmm....",
                "mmmmm...",
                "mmmmm...",
                ".mmm....",
                "..m.....",
                "........",
                "........",
            ]),
            new("Rough gauntlet", Normal, 2,
            [
                "........",
                "........",
                "ff.fffff",
                "........",
                "........",
                "fffff.ff",
                "........",
                "........",
            ]),
            new("Hidden course", Normal, 2,
            [
                "....h...",
                "...hh...",
                "..hh....",
                "...h....",
                "...h....",
                "...hh...",
                "....hh..",
                ".....hh.",
            ]),
            new("Birchwood posts", Normal, 3,
            [
                ".......",
                ".f.f.f.",
                ".......",
                ".f.f.f.",
                ".......",
                ".f.f.f.",
                ".......",
            ]),
            new("Grove flanks", Normal, 2,
            [
                "ff......",
                "f.......",
                "........",
                "........",
                ".....f..",
                "....fff.",
                "...fffff",
                "....ffff",
            ]),
            new("Green hummock", Normal, 3,
            [
                "........",
                "......h.",
                "..hhhhhh",
                "..hhhhh.",
                ".hhhhh..",
                "hhhhhh..",
                ".h......",
                "........",
            ]),
            new("Hummock litter", Normal, 2,
            [
                ".f......",
                "h....hh.",
                "h.f.h.fh",
                "...hh...",
                "...hh...",
                "hf.h.f.h",
                ".hh....h",
                "......f.",
            ]),
            new("Far terraces", Normal, 2,
            [
                "........",
                ".mmmmmm.",
                "........",
                ".hhhhhh.",
                ".hhhhhh.",
                "........",
                ".mmmmmm.",
                "........",
            ]),
            new("Raised timber", Normal, 2,
            [
                "...f..",
                "m..f..",
                "m..f..",
                "m..f..",
                "m..f..",
                "......",
            ]),
            new("Hidden bounds", Normal, 2,
            [
                ".......",
                ".fffff.",
                ".f...f.",
                ".f...f.",
                ".f...f.",
                ".f...f.",
                ".fffff.",
                ".......",
            ]),
            new("Wild crosscut", Normal, 3,
            [
                "....h...",
                "....h...",
                "....h...",
                "....h...",
                "hhhhhhhh",
                "....h...",
                "....h...",
                "....h...",
            ]),
            new("Quagmire bias", Normal, 2,
            [
                "......mm",
                ".....mm.",
                "....mm..",
                "...mm...",
                "...mm...",
                "..mm....",
                ".mm.....",
                "mm......",
            ]),
            new("Still swale", Normal, 2,
            [
                "mmmm....",
                ".mmm....",
                "m.mm....",
                "........",
                "....mm.m",
                "....mmm.",
                "....mmmm",
            ]),
            new("Old spread", Normal, 2,
            [
                "..h...ff",
                ".hhh...f",
                "..h.h...",
                "...hh...",
                "...h.h..",
                "f...hhh.",
                "ff...h..",
            ]),
            new("Sharp gauntlet", Normal, 2,
            [
                "...fff..",
                "....f...",
                "hhh.hhhh",
                "........",
                "........",
                "hfhh.hhh",
                "fff.....",
                ".f......",
            ]),
            new("Dark downland", Normal, 3,
            [
                ".m..h...",
                "mmm..hh.",
                ".m..h...",
                ".....hh.",
                ".hh.....",
                "...h..m.",
                ".hh..mmm",
                "...h..m.",
            ]),
            new("Windy stanchions", Normal, 2,
            [
                "........",
                ".f.f.f..",
                "...h....",
                ".fhhhfh.",
                "...h.hhh",
                ".f.f.fh.",
                "........",
                "........",
            ]),
            new("Windy cornerstone", Normal, 2,
            [
                "hhh.....",
                "hh......",
                "h.......",
                ".......h",
                "......hh",
                ".....hhh",
            ]),
            new("Timber redoubt", Normal, 2,
            [
                "........",
                "........",
                "..fff...",
                "..fff...",
                "...fff..",
                "...fff..",
                "........",
                "........",
            ]),
            new("Sump broken", Normal, 3,
            [
                "..h.....",
                ".......m",
                "..hhm.mm",
                "....hmmm",
                "...m..mm",
                "m.h....m",
                "m...m...",
            ]),
            new("Bramble shelves", Normal, 2,
            [
                "......",
                ".ffff.",
                "......",
                "......",
                ".ffff.",
                "......",
            ]),
            new("Raised files", Normal, 2,
            [
                "...m..h",
                "h..m..h",
                "h..m..h",
                "h..m..h",
                "h..m..h",
                "h..m..h",
                "h..m..h",
                "......h",
            ]),
            new("Fell circuit", Normal, 2,
            [
                ".......",
                ".hhhhh.",
                ".h...h.",
                ".h...h.",
                ".h...h.",
                ".h...h.",
                ".hhhhh.",
                ".......",
            ]),
            new("Bluff junction", Normal, 2,
            [
                "....h...",
                "....h...",
                "....h...",
                "hhhhhhhh",
                "....h...",
                "....h...",
                "....h...",
            ]),
            new("Grey mire", Normal, 2,
            [
                "......mm",
                ".....mm.",
                "....mm..",
                "...mm...",
                "..mm....",
                ".mm.....",
                "mm......",
                "m.......",
            ]),
            new("Quagmire halves", Normal, 2,
            [
                ".mm....",
                ".m.....",
                "mmm....",
                ".......",
                "....mmm",
                ".....m.",
                "....mm.",
            ]),
            new("Fair scatter", Normal, 2,
            [
                "........",
                "..m.....",
                ".mmmh...",
                "mmmhhmmm",
                "...hmmm.",
                ".....m..",
                "........",
            ]),
            new("Timber strait", Normal, 3,
            [
                "......",
                "......",
                "f.ffff",
                "......",
                "......",
                "ffff.f",
                "f.....",
                "ff....",
            ]),
            new("Old hummock", Normal, 2,
            [
                "...hh.",
                "..hh..",
                ".hh...",
                "hh....",
                "....hh",
                "...hh.",
                "..hh..",
                ".hh...",
            ]),
            new("Sleeping tor", Normal, 2,
            [
                ".......",
                ".h.h.h.",
                ".......",
                ".h.h.h.",
                ".......",
                ".h.h.h.",
                ".......",
            ]),
            new("Fair wedges", Normal, 2,
            [
                "mmm.....",
                "mm......",
                "m.......",
                "........",
                "........",
                ".......m",
                "......mm",
                ".....mmm",
            ]),
            new("Cold redoubt", Normal, 2,
            [
                "........",
                "........",
                "..hhhh..",
                "..hhhh..",
                "..hhhh..",
                "..hhhh..",
                "........",
                "........",
            ]),
            new("Bramble litter", Normal, 3,
            [
                ".......",
                "..mh.f.",
                "......f",
                "...h...",
                "f......",
                ".f.hm..",
                ".......",
            ]),
            new("Green layers", Normal, 2,
            [
                ".hhhh.",
                "......",
                "......",
                "......",
                "......",
                ".hhhh.",
            ]),
            new("Crooked aisles", Normal, 2,
            [
                ".......",
                ".m..m..",
                ".m..m..",
                ".m...m.",
                "..m..m.",
                "..m..m.",
                ".......",
            ]),
            new("Old perimeter", Normal, 3,
            [
                "........",
                ".mmmmmm.",
                ".m....m.",
                ".m....m.",
                ".m....m.",
                ".m....m.",
                ".mmmmmm.",
                "........",
            ]),
            new("Pale junction", Normal, 2,
            [
                "....f...",
                "....f...",
                "....f...",
                "....f...",
                "ffffffff",
                "....f...",
                "....f...",
                "....f...",
            ]),
            new("Windy morass", Normal, 3,
            [
                "mm.....",
                ".mm....",
                "..mm...",
                "...mm..",
                "..mm...",
                "...mm..",
                "....mm.",
                ".....mm",
            ]),
            new("Sleeping split", Normal, 2,
            [
                "hh.h....",
                ".hhh....",
                ".h.h....",
                ".hhh....",
                "....h.hh",
                "....h.hh",
                "....h..h",
                "....h.hh",
            ]),
            new("Hard scatter", Normal, 2,
            [
                ".......",
                ".......",
                "..m....",
                ".mmm...",
                "mmmmm..",
                "mmmmm..",
                "mmmm...",
            ]),
            new("Fen strait", Normal, 3,
            [
                "......",
                "......",
                "mmmm.m",
                "m.mmmm",
                "......",
                "......",
            ]),
            new("Sump channel", Normal, 3,
            [
                "....m...",
                "...mm...",
                "...m....",
                "....mm..",
                "..mm....",
                "....m...",
                "...mm...",
                "...m....",
            ]),
            new("Frozen timber", Normal, 2,
            [
                "........",
                "..f.f.f.",
                "........",
                "..f.f.f.",
                ".f.f.f..",
                "........",
                ".f.f.f..",
                "........",
            ]),
            new("High angles", Normal, 2,
            [
                "ff......",
                "m.......",
                "mm......",
                "m.......",
                ".......m",
                "......mm",
                ".......m",
                "......ff",
            ]),
            new("Reedbed centre", Normal, 3,
            [
                "........",
                "........",
                "..mmmm..",
                "..mmmm..",
                "..mmmm..",
                "..mmmm..",
                "........",
                "........",
            ]),
            new("Sleeping barrow", Normal, 2,
            [
                "..h...",
                "......",
                "...h.h",
                "hfh...",
                "...hfh",
                "h.h...",
                "......",
                "...h..",
            ]),
            new("Grey swale", Normal, 2,
            [
                "mmmmmmm.",
                "........",
                "........",
                ".mmmmmm.",
                "........",
                "........",
                "mmmmmmmm",
            ]),
            new("Quiet ranks", Normal, 2,
            [
                "...m..h",
                "m..m..h",
                "m..m..h",
                "m..m..h",
                "m..m..h",
                "m..m..h",
                "m..m..h",
                "......h",
            ]),
            new("Sump bounds", Normal, 2,
            [
                "......",
                ".mmmm.",
                ".m..m.",
                ".m..m.",
                ".mmmm.",
                "......",
            ]),
            new("Hidden crossing", Normal, 2,
            [
                "...m...",
                "...m...",
                "...m...",
                "mmmmmmm",
                "...m...",
                "...m...",
                "...m...",
            ]),
            new("Crooked traverse", Normal, 2,
            [
                "....mm",
                "...mm.",
                "..mm..",
                "..mm..",
                ".mm...",
                "mm....",
            ]),
            new("Sleeping knoll", Normal, 2,
            [
                "hhhh....",
                "hhhh....",
                "hhh.....",
                ".hhh....",
                "....m.m.",
                ".....mmm",
                "....mm.m",
                ".....m.m",
            ]),
            new("Sump stand", Normal, 2,
            [
                "mmm....",
                "mm.....",
                "m......",
                ".......",
                "......m",
                ".....mm",
                "....mmm",
            ]),
            new("Sleeping defile", Normal, 2,
            [
                "........",
                "........",
                "m.mmmmmm",
                "........",
                "........",
                "mmmmmm.m",
                "........",
                "........",
            ]),
            new("Fair fell", Normal, 2,
            [
                "....hh..",
                "...h....",
                "...h....",
                "....hh..",
                "..hh....",
                "....h...",
                "....h...",
                "..hh....",
            ]),
            new("Pinewood waypoints", Normal, 3,
            [
                ".....f..",
                ".m.mfff.",
                "...fffff",
                ".m.mfff.",
                ".....f..",
                ".m.m.m..",
                "........",
            ]),
            new("Broad barrow", Normal, 2,
            [
                "hhh...",
                "hh....",
                "h.....",
                "..h.h.",
                ".h.h..",
                ".....h",
                "....hh",
                "...hhh",
            ]),
            new("Quagmire redoubt", Normal, 2,
            [
                ".......",
                ".......",
                "..mmm..",
                "..mmm..",
                "..mmm..",
                "..mmm..",
                ".......",
                ".......",
            ]),
            new("Even hummock", Normal, 2,
            [
                "..h...",
                "...h..",
                "h.hh..",
                "..hh.h",
                "..h...",
                "...h..",
            ]),
            new("Grove layers", Normal, 3,
            [
                ".ffffff.",
                "........",
                "........",
                ".ffffff.",
                ".ffffff.",
                "........",
                "........",
                ".ffffff.",
            ]),
            new("Hillock stalls", Normal, 2,
            [
                ".h......",
                ".h..h..h",
                ".h..h..h",
                ".h..h..h",
                ".h..h..h",
                ".h..h..h",
                ".h..h..h",
            ]),
            new("Sump enclosure", Normal, 2,
            [
                "........",
                ".mmmmmm.",
                ".m....m.",
                ".m....m.",
                ".m....m.",
                ".m....m.",
                ".mmmmmm.",
                "........",
            ]),
            new("Sleeping hillock", Normal, 3,
            [
                "....h...",
                "....h...",
                "....h...",
                "hhhhhhhh",
                "....h...",
                "...hhh..",
                "..hhhhh.",
            ]),
            new("Open coppice", Normal, 3,
            [
                "ff......",
                ".ff.....",
                "..ff....",
                "...ff...",
                "...ff...",
                "....ff..",
                ".....ff.",
                "......ff",
            ]),
            new("Green morass", Fun, 2,
            [
                ".mmmmmm.",
                "........",
                "........",
                "........",
                ".mmmmmm.",
            ]),
            new("Dark stalls", Fun, 3,
            [
                ".M....",
                ".M..f.",
                ".M..f.",
                ".M..f.",
                ".M..f.",
                ".M..f.",
                ".M..f.",
                ".M..f.",
            ]),
            new("Rough escarpment", Fun, 3,
            [
                "hh..hMM",
                "M.....M",
                "M.....M",
                "M.....M",
                "M.....M",
                "M.....M",
                "M.....M",
                ".....MM",
            ]),
            new("Soft crosscut", Fun, 2,
            [
                "....m...",
                "....m...",
                "mmmmmmmm",
                "...m....",
                "...m....",
            ]),
            new("Greenwood slant", Fun, 2,
            [
                "fff...",
                "ff....",
                "f.f...",
                "...f.f",
                "....ff",
                "...fff",
            ]),
            new("Cold hillock", Fun, 3,
            [
                "h.h...",
                ".hh...",
                "hhh...",
                "...hhh",
                "...hh.",
                "...h.h",
            ]),
            new("Mire spread", Fun, 3,
            [
                ".....mmm",
                "....mmmm",
                ".....mmm",
                ".f....f.",
                "mmm.....",
                "mmmm....",
                "mmm.....",
            ]),
            new("Pale strait", Fun, 3,
            [
                ".....",
                ".....",
                "h...M",
                "...MM",
                "..MMM",
                ".h.hM",
                "..hhM",
                ".h..M",
            ]),
            new("Morass wander", Fun, 3,
            [
                "..m..",
                "..m..",
                "..mm.",
                "..mm.",
                "m.m..",
                "mm.mm",
                "m.m.m",
                ".mmmm",
            ]),
            new("Mire studs", Fun, 3,
            [
                ".....m..",
                ".m.mmmm.",
                "...mmmmm",
                ".m.mmmm.",
                ".mmmm.m.",
                "mmmmm...",
                ".mmmm.m.",
                "..m.....",
            ]),
            new("Hillock bookends", Fun, 2,
            [
                "hhh..",
                "hh...",
                "h....",
                ".....",
                ".....",
                "....h",
                "...hh",
                "..hhh",
            ]),
            new("Bright redoubt", Fun, 3,
            [
                ".......",
                ".....m.",
                "..mmmmm",
                "..mmmmm",
                "mmmmm..",
                "mmmmm..",
                ".m.....",
                ".......",
            ]),
            new("Sharp broken", Fun, 2,
            [
                "h.....",
                ".h..h.",
                "h.h...",
                "..hh..",
                "..h..h",
                "....hh",
                "...h..",
                "hhh...",
            ]),
            new("Coppice terraces", Fun, 2,
            [
                "........",
                "fffffff.",
                "........",
                ".fffffff",
                "........",
            ]),
            new("Pale canyon", Fun, 2,
            [
                ".....",
                ".h..C",
                ".C..C",
                ".C..C",
                ".C..C",
                ".C..C",
                ".h..C",
                "....C",
            ]),
            new("Wetland enclosure", Fun, 2,
            [
                ".......",
                ".mmmmm.",
                ".m...m.",
                ".m...m.",
                ".m...m.",
                ".mmmmm.",
                ".......",
            ]),
            new("Pale woodland", Fun, 2,
            [
                "...ff...",
                "...ff...",
                "ffffffff",
                "ffffffff",
                "...ff...",
                "...ff...",
            ]),
            new("Ridge traverse", Fun, 2,
            [
                "hh.hC",
                "hhhC.",
                "hhC..",
                "hC...",
                "Ch...",
                "hhh..",
                ".h...",
                ".....",
            ]),
            new("High hummock", Fun, 2,
            [
                "..m....",
                "mmm....",
                "mmm....",
                "mmm....",
                "....hhh",
                ".....hh",
                "....h.h",
                "...hhhh",
            ]),
            new("High cairn", Fun, 2,
            [
                "........",
                "........",
                "........",
                "......M.",
                ".M.f.MMM",
                "MMMfM.M.",
                "h.f.MM..",
                "fMffM...",
            ]),
            new("Raised gauntlet", Fun, 2,
            [
                "........",
                "mm.mmmmm",
                "........",
                "mmmmm.mm",
                "........",
            ]),
            new("Copse wander", Fun, 2,
            [
                "...ff.",
                "....ff",
                "...ff.",
                ".ff...",
                "ff....",
                ".ff...",
            ]),
            new("Hidden rise", Fun, 2,
            [
                "........",
                "..h.h.h.",
                "........",
                "..h.h.h.",
                "..h.....",
                ".hhhh.hh",
                "hhhhh.hh",
                ".hhh...h",
            ]),
            new("Bog cornerstone", Fun, 2,
            [
                "mmm...",
                "mm....",
                "m.....",
                ".....m",
                "....mm",
                "...mmm",
            ]),
            new("Woodland redoubt", Fun, 2,
            [
                "..ffff",
                "...fff",
                "..CCf.",
                "..CC..",
                "..CC..",
                "......",
                "..f...",
                ".fff..",
            ]),
            new("Quiet mottle", Fun, 2,
            [
                "....M..M",
                ".m...CmM",
                ".MmC.M..",
                "m...C...",
                ".mC..CC.",
                "...m....",
                ".hh.hM.C",
            ]),
            new("Hard tiers", Fun, 3,
            [
                ".mmmmmm",
                ".......",
                ".......",
                "mmmmmmm",
                ".......",
                ".......",
                "mmmmmm.",
            ]),
            new("Sleeping morass", Fun, 2,
            [
                ".m.....m",
                ".m..m..m",
                ".m..m..m",
                ".m..m..m",
                ".m..m..m",
                ".m..m..m",
                ".m..m...",
            ]),
            new("Windy abyss", Fun, 2,
            [
                ".h.hC",
                "h...C",
                "C...C",
                "C...C",
                "C...C",
                "C...C",
                "....C",
                "hh..C",
            ]),
            new("Short bastion", Fun, 3,
            [
                "..M..",
                "..M..",
                "..hM.",
                "..MMM",
                "MMM..",
                "..M..",
                "..M..",
                "..M..",
            ]),
            new("Dark oblique", Fun, 2,
            [
                "M....",
                "...M.",
                "..MMM",
                "...M.",
                ".M...",
                "MMM..",
                ".h.M.",
                "....M",
            ]),
            new("Crag split", Fun, 2,
            [
                "..MM....",
                ".hMM....",
                "MMMM....",
                ".MM.....",
                ".....MM.",
                "....MMMM",
                ".....hMM",
                "....hM.M",
            ]),
            new("Bramble drift", Fun, 2,
            [
                "ffhMM...",
                "ff.M....",
                "fff.....",
                ".f.ff.f.",
                ".....fff",
                "....M.ff",
                "....MMff",
            ]),
            new("Fissure gauntlet", Fun, 2,
            [
                ".....CC.",
                "...hhhCC",
                "hhhhCCCh",
                ".....C..",
                "..C.....",
                "hCCChhhh",
                "h.hCC...",
                "..CC....",
            ]),
            new("Sunken abyss", Fun, 2,
            [
                ".....hCC",
                "...hhhCC",
                "..C..C..",
                "...h.CC.",
                ".h.h.hCC",
            ]),
            new("Deep pegs", Fun, 2,
            [
                "...mmmmm",
                "..m.mmm.",
                ".....m..",
                "..m.m.m.",
                ".m.m.m..",
                "..m.....",
                ".mmm.m..",
                "mmmmm...",
            ]),
            new("Open bookends", Fun, 3,
            [
                "hCC.fff",
                "CC...ff",
                "C.....f",
                ".......",
                ".......",
                "f.....C",
                "ff...CC",
                "fff.hCC",
            ]),
            new("Hidden pinewood", Fun, 3,
            [
                "......",
                ".fff..",
                ".fff..",
                "..fff.",
                "..fff.",
                "......",
            ]),
            new("Deep mottle", Fun, 2,
            [
                "C.C.hh..",
                "h..C....",
                ".hhhh.hh",
                "...CC...",
                "hh.hhhh.",
                "....C..h",
                "..hh.C.C",
            ]),
            new("Still greenwood", Fun, 2,
            [
                ".ffffff",
                ".......",
                "M......",
                "MMffMf.",
                "M..MMM.",
                "....M..",
                ".mmmmm.",
            ]),
            new("Coppice files", Fun, 2,
            [
                "..f..",
                "h.f.f",
                "h.f.f",
                "h.f.f",
                "f.f.h",
                "f.f.h",
                "f.f.h",
                "..f..",
            ]),
            new("Scarp enclosure", Fun, 3,
            [
                ".h...hMM",
                "......MM",
                "M......M",
                ".hM....M",
                "hhhhhhMM",
            ]),
            new("Slough fourways", Fun, 2,
            [
                "...mm...",
                "...mm...",
                "...mm...",
                "mmmmmmmm",
                "mmmmmmmm",
                "...mm...",
                "...mm...",
                "...mm...",
            ]),
            new("Lost void", Fun, 2,
            [
                "......CC",
                ".....CC.",
                "....CC..",
                "...CCm..",
                "..CCmmm.",
                ".CC..m..",
                "CC......",
            ]),
            new("Bare divide", Fun, 2,
            [
                ".MM....",
                ".MM....",
                "MMM....",
                ".MM....",
                "....MM.",
                "....MMM",
                "....MM.",
                "....MM.",
            ]),
            new("Even birchwood", Fun, 2,
            [
                "..f...",
                ".fff..",
                "fffff.",
                ".fffff",
                "..fff.",
                "...f..",
            ]),
            new("Rough strait", Fun, 3,
            [
                "..C.....",
                "...C...C",
                "hh....CC",
                ".CCCCCC.",
                "h...h.CC",
                "h...hCC.",
                ".....C..",
            ]),
            new("Cold copse", Fun, 3,
            [
                "..ff.",
                "..ff.",
                ".f...",
                "f....",
                "f..f.",
                ".ffff",
                ".ffff",
                ".ffff",
            ]),
            new("Low timber", Fun, 2,
            [
                "...fff.f",
                ".f.fffff",
                ".....fff",
                ".f.f.fff",
                ".......f",
                ".f.f.f..",
                "........",
                "........",
            ]),
            new("Bright cornerstone", Fun, 2,
            [
                "..h...MM",
                "hh....MM",
                "M......M",
                "h.....MM",
                "hh....MM",
            ]),
            new("Wetland centre", Fun, 2,
            [
                ".....",
                "m....",
                "mmM..",
                "m.m..",
                "..m.m",
                "..Mmm",
                "....m",
                ".....",
            ]),
            new("Fen fleck", Fun, 2,
            [
                "...mm...",
                "..m..C.C",
                "m.C..C.m",
                "C.C..m..",
                "...mm...",
            ]),
            new("Quiet layers", Fun, 2,
            [
                "........",
                "ffffffff",
                "........",
                ".ffffff.",
                ".ffffff.",
                "........",
                "ffffffff",
                "........",
            ]),
            new("Rift stalls", Fun, 2,
            [
                ".C..h.",
                ".C..h.",
                ".C..h.",
                ".h..C.",
                ".h..C.",
                ".h..C.",
            ]),
            new("Lost perimeter", Fun, 2,
            [
                "..C...",
                ".hhCC.",
                ".CC.C.",
                ".C.CC.",
                "...CC.",
                "...C..",
            ]),
            new("Blunt hillock", Fun, 2,
            [
                "...hh...",
                "...hh...",
                "hhhhhhhh",
                "hhhhhhhh",
                "...hh...",
                "...hh...",
                "...hh...",
            ]),
            new("Abyss traverse", Fun, 2,
            [
                "h.....",
                ".h....",
                "..h.C.",
                "...CCC",
                "C.CCCC",
                "CC.CCC",
                "C...C.",
                "......",
            ]),
            new("Wild checker", Fun, 2,
            [
                "hhh...",
                "h.h...",
                "hhh...",
                "..h...",
                "....M.",
                "...MMM",
                "...M.M",
                "...MM.",
            ]),
            new("Silver spread", Fun, 2,
            [
                "...ffff",
                "....fff",
                ".....ff",
                "......f",
                "f......",
                "ff.....",
                "fff....",
                "ffff...",
            ]),
            new("Low narrows", Fun, 2,
            [
                "hMM.....",
                ".hMM....",
                "MMMMMM.M",
                ".M......",
                "......M.",
                "M.MMMMMM",
                "....hhMM",
                ".....hMM",
            ]),
            new("Near channel", Fun, 2,
            [
                "..m.h...",
                ".mmmh...",
                "mmmmmh..",
                ".mmm.h..",
                "..m..h..",
            ]),
            new("Golden studs", Fun, 2,
            [
                "....ff",
                ".f.fff",
                "....ff",
                ".f.f.f",
                ".f....",
                "fff...",
            ]),
            new("Fair angles", Fun, 2,
            [
                "hhh..hCC",
                "h.....CC",
                "C......C",
                "C......C",
                "hh....CC",
                ".hh...CC",
            ]),
            new("Coppice keep", Fun, 3,
            [
                "........",
                "f.......",
                "fffff...",
                "ffffffff",
                "...fffff",
                ".......f",
                "........",
            ]),
            new("Still litter", Fun, 2,
            [
                "..f.MM",
                "M..f.h",
                "..h...",
                "...h..",
                "h.f..M",
                "MM.f..",
            ]),
            new("Wild tiers", Fun, 2,
            [
                "......",
                "...CC.",
                "......",
                "hhhhh.",
                ".hhhhh",
                "......",
                "..h.CC",
                "......",
            ]),
            new("Escarpment tiers", Mad, 2,
            [
                "h..hhMM.",
                "........",
                "........",
                ".MMMMMMM",
                "..M...MM",
                ".MMM.MMM",
                "hh.h..MM",
                ".hhM...M",
            ]),
            new("High pinewood", Mad, 2,
            [
                "....f...",
                "f.f.f.M.",
                "f.f.f.M.",
                "f.f.f.M.",
                "f.f.f.M.",
                "f.f.f.M.",
            ]),
            new("Near hummock", Mad, 2,
            [
                ".h....",
                "hhhhh.",
                "hhhhh.",
                "hhhhh.",
                ".h.hh.",
                ".h..h.",
                ".hhhh.",
                "......",
            ]),
            new("Cairn quarters", Mad, 3,
            [
                "...MM.f.",
                ".h.MMfff",
                "hh.h.MfM",
                "...MM...",
                "...MM...",
            ]),
            new("Soft oblique", Mad, 2,
            [
                "h..hhhhh",
                ".h..hhh.",
                "..h..h..",
                "...hhhh.",
            ]),
            new("Knoll checker", Mad, 2,
            [
                "hh..",
                "hh..",
                "hh..",
                "hh..",
                "..CC",
                "..hC",
                ".hhh",
                "..hC",
            ]),
            new("Near scarp", Mad, 1,
            [
                "ff.MMf..",
                "fMMMMM..",
                "ffMMM...",
                ".fMM....",
            ]),
            new("Scarp passage", Mad, 1,
            [
                "........",
                "MMM.MMMM",
                "MMMM.MMM",
                "........",
            ]),
            new("Gulf snake", Mad, 2,
            [
                "..f.",
                "...f",
                "...f",
                "..Cf",
                ".CCC",
                "CCCC",
                ".h.C",
                "..hC",
            ]),
            new("Wild swale", Mad, 2,
            [
                ".mmmmmmm",
                ".Mmmmmmm",
                "...m..mm",
                ".......m",
            ]),
            new("Bog bookends", Mad, 2,
            [
                "mmm..mmm",
                "mm....mm",
                "m......m",
                "mm....mm",
                "mmm..mmm",
            ]),
            new("Green sinkhole", Mad, 2,
            [
                "......",
                "......",
                ".CCC..",
                "CCCC..",
                "CCCC..",
                "CCCC..",
                ".hCC..",
                "hCC...",
            ]),
            new("Pale broken", Mad, 2,
            [
                "..M.M.",
                "...hMM",
                "C.MMMM",
                "...MMM",
                "C...M.",
                ".h..MM",
            ]),
            new("Grey barrow", Mad, 2,
            [
                ".....",
                ".hhh.",
                ".....",
                ".CCCC",
                ".....",
                ".CMM.",
                "h.C..",
                "hChhh",
            ]),
            new("Sinkhole ranks", Mad, 2,
            [
                "..C.C.",
                "f.C.C.",
                "f.C.C.",
                "f.C.C.",
                "f.C.C.",
                "f.C.C.",
                "f.C.C.",
                "f...C.",
            ]),
            new("Bramble perimeter", Mad, 2,
            [
                "..fff...",
                ".ffffff.",
                "fffff.f.",
                "ffff..f.",
                "fff...f.",
                ".ffffff.",
                "........",
            ]),
            new("Silver reedbed", Mad, 2,
            [
                ".m..m...",
                "mmm.m...",
                ".mmmm...",
                "mmmmm...",
                "mmmmmmmm",
                "..m.m...",
                "....m...",
                "....m...",
            ]),
            new("Still escarpment", Mad, 2,
            [
                "fM....",
                "hMM...",
                "MMMM..",
                "MMMMM.",
                "...hMM",
                "..hMMf",
            ]),
            new("Coppice patchwork", Mad, 2,
            [
                "ff...",
                "ff...",
                "fff..",
                "ff...",
                "..f.C",
                ".fffC",
                "fffff",
                ".fffC",
            ]),
            new("Far stand", Mad, 2,
            [
                ".....",
                ".....",
                "...h.",
                "..hhh",
                ".hhhh",
                ".hhhh",
                "hhhh.",
                "hhhh.",
            ]),
            new("Rough defile", Mad, 3,
            [
                "h....hCC",
                "f..CffCf",
                "..C.....",
                "fffff.ff",
                "........",
            ]),
            new("Bastion meander", Mad, 2,
            [
                "....h.MM",
                "....hhMM",
                "...CCMMM",
                "...CC.M.",
                "h.CC....",
                "hMC.....",
            ]),
            new("High waypoints", Mad, 2,
            [
                "h.......",
                "hh..C.C.",
                "hhh.....",
                "hhC.C.C.",
                "h.h.....",
                ".hhhC.C.",
                "hhhhh...",
            ]),
            new("Crooked crag", Mad, 2,
            [
                "hh..M",
                ".hhhM",
                "MM.MM",
                "MMM.M",
                "MM...",
                "M...M",
                "...hM",
                "..hhM",
            ]),
            new("Woodland hub", Mad, 2,
            [
                "f...",
                "ff..",
                "fM..",
                ".M..",
                "fM..",
                "ff..",
                "fff.",
                "ff..",
            ]),
            new("Open mottle", Mad, 2,
            [
                ".C.Cm.",
                "....m.",
                "m...MC",
                "..m.m.",
                "..C.MM",
                "mm.C.C",
                "..MCm.",
                ".MM...",
            ]),
            new("Sharp mire", Mad, 3,
            [
                ".....",
                "mmmm.",
                "mm...",
                "mCCCC",
                ".....",
                "...hC",
                ".....",
                ".mmmm",
            ]),
            new("Sunken woodland", Mad, 3,
            [
                "f...",
                "f.f.",
                "f.f.",
                "f.f.",
                "f.f.",
                "f.f.",
                "f.f.",
                "..f.",
            ]),
            new("Open bastion", Mad, 2,
            [
                "M.....",
                ".MmmM.",
                "Mm.MMM",
                ".m..M.",
                ".mmmm.",
                "......",
            ]),
            new("Near crevasse", Mad, 2,
            [
                "...CC...",
                "...CC...",
                "CCCCCCCC",
                "CCCCCCCC",
                "...CC...",
                "...CC...",
                "...CC...",
            ]),
            new("Low bias", Mad, 2,
            [
                "fffffff",
                "ffffff.",
                ".ffff..",
                "..ff...",
                ".ff....",
                "ff.....",
                "f......",
                ".......",
            ]),
            new("Bramble patchwork", Mad, 3,
            [
                "ffff....",
                "ffff....",
                "fffff...",
                ".fff.M.M",
                "..f...MM",
                "....h.MM",
            ]),
            new("Long coppice", Mad, 3,
            [
                ".CC..f..",
                "CC..fff.",
                "C..fffff",
                "....hCf.",
                "...hhhC.",
                "...hh.CC",
            ]),
            new("Cairn defile", Mad, 3,
            [
                "....",
                "..M.",
                "h..M",
                "MMMM",
                ".MMM",
                "hh.M",
                "...M",
                "..M.",
            ]),
            new("Canyon course", Mad, 2,
            [
                "..f.",
                "...f",
                "..Cf",
                ".CCC",
                "..C.",
                ".Cff",
                "h.C.",
                "fC..",
            ]),
            new("Crooked reedbed", Mad, 3,
            [
                "......",
                ".mC.C.",
                "mmm...",
                "mmmmC.",
                "mmm...",
                ".mm.C.",
                ".mmm..",
                "..m...",
            ]),
            new("Deep bastion", Mad, 2,
            [
                "h.h.hMM",
                ".h...MM",
                "M..M..M",
                "..MMM..",
                ".MMMMM.",
                "M.MMM.M",
                "...h.MM",
                "..h..MM",
            ]),
            new("Long hub", Mad, 3,
            [
                "....",
                "..M.",
                ".hhM",
                "MMMM",
                ".MMM",
                "..M.",
                "..M.",
                ".M..",
            ]),
            new("Silver litter", Mad, 2,
            [
                "hM.C.mmm",
                "....M...",
                "M.m.CC..",
                "MC.M...M",
                ".C.mM.m.",
                "C.MMC.mM",
                ".m...C..",
                "hhhMCm..",
            ]),
            new("Sleeping rift", Mad, 2,
            [
                "h..h.hCC",
                "........",
                ".CCCCCCC",
                ".......C",
                "CCCCCCCC",
                ".....CCC",
                ".hh.h.CC",
                ".......C",
            ]),
            new("Bramble stalls", Mad, 3,
            [
                ".C..f.f.",
                ".CC.f.f.",
                "fCC.f.f.",
                "f.C.f.f.",
                "f.C.f.f.",
                "f.C.f.f.",
                "f...f.f.",
            ]),
            new("Pinewood bounds", Mad, 3,
            [
                "ffffffff",
                "f......f",
                "f......f",
                "f......f",
                "f......f",
                "f......f",
                "f......f",
                "ffffffff",
            ]),
            new("Abyss junction", Mad, 3,
            [
                "...CC...",
                "....CC..",
                "..hhhCC.",
                "CCCCCCCC",
                "CCCCCCCC",
                "...CC...",
                "...CC...",
                "...CC...",
            ]),
            new("Crag traverse", Mad, 2,
            [
                "..Mmm",
                ".h.M.",
                ".mM..",
                "mm...",
                "M....",
                "MM...",
                "hhM..",
                "hM...",
            ]),
            new("Broad rift", Outlandish, 3,
            [
                "Cmmmm",
                "CC...",
                "CCCM.",
                "CC...",
                "CCCCC",
            ]),
            new("Summit ranks", Outlandish, 2,
            [
                "....",
                ".M.C",
                ".M.C",
                "MM.C",
                "MM.C",
                "MMMC",
            ]),
            new("Pale ring", Outlandish, 2,
            [
                "MMMM",
                "M..M",
                "M..M",
                "M..M",
                "M..M",
                "M..M",
                "M..M",
                "MMMM",
            ]),
            new("Summit fourways", Outlandish, 2,
            [
                "MMMMM",
                ".MMMM",
                "ffMMM",
                "..f.M",
                "..f..",
            ]),
            new("Spur oblique", Outlandish, 2,
            [
                "hMM",
                ".hM",
                "M.h",
                "MM.",
                "MMM",
                "MM.",
                "M..",
                "...",
            ]),
            new("Blunt patchwork", Outlandish, 2,
            [
                "CC..",
                "CC..",
                ".C..",
                "CCCC",
                ".CCC",
                ".CCC",
            ]),
            new("Silent spread", Outlandish, 1,
            [
                "ffffC...",
                "fffC....",
            ]),
            new("Long bog", Outlandish, 2,
            [
                "....m...",
                "MMMmmmMM",
                "..mmmmm.",
            ]),
            new("Narrow snake", Outlandish, 2,
            [
                "fff..",
                ".fff.",
                "..fff",
                ".ffff",
                "..fff",
            ]),
            new("Sharp waypoints", Outlandish, 2,
            [
                "..fff",
                ".ffff",
                "fffff",
                ".ffff",
                "..f..",
            ]),
            new("Scarp cornerstone", Outlandish, 2,
            [
                "MMM.",
                "MM..",
                "M...",
                "...M",
                ".MMM",
                "MMMM",
            ]),
            new("Near swale", Outlandish, 2,
            [
                "....",
                ".Cm.",
                ".mmm",
                "mmmm",
                "mmmm",
                ".mm.",
            ]),
            new("Long mottle", Outlandish, 2,
            [
                "mmm",
                ".mm",
                "..m",
                "M..",
                "m..",
                "mm.",
                "mmm",
                "mm.",
            ]),
            new("Deep greenwood", Outlandish, 1,
            [
                "...f....",
                "ffffffff",
            ]),
            new("Deep files", Outlandish, 2,
            [
                "..",
                "M.",
                "MM",
                "MM",
                "MM",
                "MM",
                "M.",
                "M.",
            ]),
            new("Rampart ring", Outlandish, 2,
            [
                "MMMMMM",
                "M....M",
                "M....M",
                "MMMMMM",
            ]),
            new("Hidden pinnacle", Outlandish, 2,
            [
                "M.M..",
                "MMM..",
                "MMMMM",
                "MMMM.",
                "MMM..",
            ]),
            new("Greenwood bias", Outlandish, 3,
            [
                "fC",
                "ff",
                "ff",
                "ff",
                "f.",
                "..",
                "..",
                "..",
            ]),
            new("Soft greenwood", Outlandish, 1,
            [
                "fffff...",
                ".fffMMM.",
            ]),
            new("Sinkhole spread", Outlandish, 2,
            [
                "....",
                "....",
                "C...",
                "CCC.",
                "CCCC",
                "CCCC",
                "CMCC",
                "MMM.",
            ]),
            new("Pale defile", Outlandish, 2,
            [
                "..",
                "M.",
                "MM",
                "M.",
                "..",
                "MM",
                "MM",
                "MM",
            ]),
            new("Near quagmire", Outlandish, 2,
            [
                "..Mmm",
                ".Mmmm",
                "m.Mmm",
                "mmM.m",
                "mMM..",
            ]),
            new("Knoll studs", Outlandish, 1,
            [
                "....hhhh",
                "...hhhhh",
            ]),
            new("Trench angles", Outlandish, 1,
            [
                "CCCCC.MM",
                "MCCC...M",
                "MMC...CC",
            ]),
            new("Crag hub", Outlandish, 2,
            [
                "M.",
                "MM",
                "M.",
                "h.",
                "M.",
                "MM",
                "MM",
                "MM",
            ]),
            new("Blunt litter", Outlandish, 1,
            [
                ".hCC..Ch",
                "Ch.h..Ch",
            ]),
            new("Spur tiers", Outlandish, 1,
            [
                ".....MMM",
                "CCCCMMMM",
                ".....MMM",
                "MMMMMMMM",
            ]),
            new("Windy palisade", Outlandish, 2,
            [
                ".Mh..h.h",
                ".hhhhhhh",
                "hhhhhh.h",
                ".hhhM...",
            ]),
            new("Bastion enclosure", Outlandish, 2,
            [
                "MMMM",
                "M..M",
                "M..M",
                "M..M",
                "M..M",
                "M..M",
                "M..M",
                "MMMM",
            ]),
            new("Windy crosscut", Outlandish, 2,
            [
                "CC.",
                "CC.",
                "CC.",
                "CCC",
                "CCC",
                "CC.",
                "CC.",
                "CC.",
            ]),
            new("Spur slant", Outlandish, 1,
            [
                "MM..MMM.",
                ".MMMMMMM",
            ]),
            new("Crooked birchwood", Outlandish, 2,
            [
                "ffff....",
                "..ffff..",
                ".ffffffC",
            ]),
            new("Lost tor", Outlandish, 2,
            [
                ".Ch.",
                "Chhh",
                "hhhh",
                "hhhh",
                "hhh.",
                "h...",
            ]),
            new("Raised gulf", Outlandish, 2,
            [
                "...",
                "..C",
                "fCC",
                "CCC",
                ".CC",
                "f.C",
                ".C.",
                "CCC",
            ]),
            new("Hard hillock", Outlandish, 2,
            [
                ".h",
                "hh",
                "fh",
                "f.",
                ".f",
                ".f",
                "h.",
                "hh",
            ]),
            new("Bare pinnacle", Outlandish, 3,
            [
                "..",
                "..",
                "M.",
                "MM",
                "MM",
                "MM",
                "MM",
                "MM",
            ]),
            new("Knoll bookends", Outlandish, 2,
            [
                "fhh",
                "Cfh",
                "C.f",
                "...",
                "...",
                "f.C",
                "fhC",
                "hhh",
            ]),
            new("Soft centre", Outlandish, 1,
            [
                "CCCCCCC.",
                ".C.CCC..",
            ]),
            new("Sharp pinnacle", Outlandish, 1,
            [
                "MMMM....",
                "MMMMM..M",
                ".MMM....",
                "mMMM.m..",
            ]),
            new("Old fissure", Outlandish, 1,
            [
                ".CCCCCCC",
                "...CCC..",
            ]),
            new("Single square", Insane, 1,
            [
                ".",
            ]),
            new("One stone", Insane, 1,
            [
                "M",
            ]),
            new("The void", Insane, 1,
            [
                "C",
            ]),
            new("Two squares", Insane, 1,
            [
                "..",
                "..",
            ]),
            new("Pin", Insane, 1,
            [
                ".",
            ]),
            new("Full stop", Insane, 1,
            [
                "m",
            ]),
            new("All chasm", Insane, 2,
            [
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
            ]),
            new("All mountain", Insane, 2,
            [
                "MMMMMMMM",
                "MMMMMMMM",
                "MMMMMMMM",
                "MMMMMMMM",
                "MMMMMMMM",
                "MMMMMMMM",
                "MMMMMMMM",
                "MMMMMMMM",
            ]),
            new("All marsh", Insane, 2,
            [
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
            ]),
            new("One lane", Insane, 1,
            [
                "........",
            ]),
            new("One file", Insane, 1,
            [
                ".",
                ".",
                ".",
                ".",
                ".",
                ".",
                ".",
                ".",
            ]),
            new("Wall to wall", Insane, 1,
            [
                "MMMMMMMM",
                "........",
                "MMMMMMMM",
            ]),
            new("Chasm lane", Insane, 1,
            [
                "CCCCCCCC",
                "........",
                "CCCCCCCC",
            ]),
            new("Deep and thin", Insane, 4,
            [
                "..",
                "..",
                "..",
                "..",
                "..",
                "..",
                "..",
                "..",
            ]),
            new("Flat and wide", Insane, 1,
            [
                "........",
                "........",
            ]),
            new("Zone overlap", Insane, 8,
            [
                "........",
                "........",
                "........",
                "........",
                "........",
                "........",
                "........",
                "........",
            ]),
            new("Nearly nothing", Insane, 1,
            [
                "C.C",
            ]),
            new("Needle", Insane, 1,
            [
                ".",
                "M",
                ".",
                "M",
                ".",
                "M",
                ".",
                ".",
            ]),
            new("Chequer", Insane, 2,
            [
                "C.C.C.C.",
                ".C.C.C.C",
                "C.C.C.C.",
                ".C.C.C.C",
                "C.C.C.C.",
                ".C.C.C.C",
                "C.C.C.C.",
                ".C.C.C.C",
            ]),
            new("Mountain chequer", Insane, 2,
            [
                "M.M.M.M.",
                ".M.M.M.M",
                "M.M.M.M.",
                ".M.M.M.M",
                "M.M.M.M.",
                ".M.M.M.M",
                "M.M.M.M.",
                ".M.M.M.M",
            ]),
            new("Two islands", Insane, 2,
            [
                "..CCCC..",
                "..CCCC..",
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
                "CCCCCCCC",
                "..CCCC..",
                "..CCCC..",
            ]),
            new("The moat", Insane, 2,
            [
                "CCCCCCCC",
                "C......C",
                "C.MMMM.C",
                "C.MMMM.C",
                "C.MMMM.C",
                "C.MMMM.C",
                "C......C",
                "CCCCCCCC",
            ]),
            new("Sealed", Insane, 1,
            [
                "MMM",
                "M.M",
                "MMM",
            ]),
            new("Marsh sea", Insane, 3,
            [
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
                "mm....mm",
                "mm....mm",
                "mmmmmmmm",
                "mmmmmmmm",
                "mmmmmmmm",
            ]),
            new("Spine", Insane, 1,
            [
                "...M...",
                "...M...",
                "...M...",
                "...M...",
                "...M...",
                "...M...",
                "...M...",
            ]),
            new("Hourglass", Insane, 2,
            [
                "........",
                ".CCCCCC.",
                "..CCCC..",
                "...CC...",
                "...CC...",
                "..CCCC..",
                ".CCCCCC.",
                "........",
            ]),
            new("Ladder", Insane, 1,
            [
                "M.M.M.M.",
                "........",
                "M.M.M.M.",
                "........",
                "M.M.M.M.",
                "........",
                "M.M.M.M.",
                "........",
            ]),
            new("Trapped", Insane, 1,
            [
                "CCCCCCCC",
                "C..MM..C",
                "C.MMMM.C",
                "CCMMMMCC",
                "CCMMMMCC",
                "C.MMMM.C",
                "C..MM..C",
                "CCCCCCCC",
            ]),
            new("Bottleneck", Insane, 2,
            [
                "........",
                "MMM..MMM",
                "MMM..MMM",
                "MMM..MMM",
                "MMM..MMM",
                "MMM..MMM",
                "MMM..MMM",
                "........",
            ]),
            new("Rubble", Insane, 2,
            [
                "MCMCMCMC",
                "CMCMCMCM",
                "MCMCMCMC",
                "CMCMCMCM",
                "MCMCMCMC",
                "CMCMCMCM",
                "MCMCMCMC",
                "CMCMCMCM",
            ]),
            new("Thin ice", Insane, 1,
            [
                "mmmmmmmm",
            ]),
            new("Last stand", Insane, 1,
            [
                "CCCCCCC",
                "C.....C",
                "C.CCC.C",
                "C.C.C.C",
                "C.CCC.C",
                "C.....C",
                "CCCCCCC",
            ]),
            new("Slot", Insane, 1,
            [
                "MM.MM",
            ]),
            new("Corner to corner", Insane, 1,
            [
                "...CCCCC",
                "....CCCC",
                "C....CCC",
                "CC....CC",
                "CCC....C",
                "CCCC....",
                "CCCCC...",
                "CCCCCC..",
            ]),
            new("Wafer", Insane, 1,
            [
                "hhhhhhhh",
            ]),
            new("Grain of sand", Insane, 1,
            [
                "h",
            ]),
        ];
    }
}
