namespace Strikers.Core;

public static partial class Library
{
    private static IReadOnlyList<ArmyDesign> AllArmies()
    {
        return
        [
            new("Bold edge", Normal, ["Leaplasher", "Clawstrider"]),
            new("Steady watch", Normal, ["Tremortusk", "Snapmaw", "Scrounger"]),
            new("Tame volley", Normal, ["Longleg", "Scrapper", "Scrounger"]),
            new("New fist", Normal, ["Plowhorn", "Lancehorn", "Plowhorn"]),
            new("Still volley", Normal, ["Scrapper", "Ravager"]),
            new("Cold volley", Normal, ["Longleg", "Scrapper", "Ravager"]),
            new("Swift front", Normal, ["Rockbreaker"]),
            new("Odd rush", Normal, ["Charger", "Charger", "Leaplasher"]),
            new("High chain", Normal, ["Lancehorn", "Plowhorn", "Bristleback", "Plowhorn"]),
            new("Wary edge", Normal, ["Tracker Burrower", "Spikesnout", "Tracker Burrower", "Leaplasher"]),
            new("Grim charge", Normal, ["Lancehorn", "Bristleback", "Plowhorn", "Lancehorn"]),
            new("Wild shadow", Normal, ["Stalker"]),
            new("Keen delve", Normal, ["Bilegut", "Tracker Burrower"]),
            new("Sharp shadow", Normal, ["Stalker"]),
            new("High arc", Normal, ["Thunderjaw", "Ravager"]),
            new("Quiet front", Normal, ["Glinthawk", "Charger", "Skydrifter"]),
            new("Deep circle", Normal, ["Thunderjaw", "Skydrifter"]),
            new("Still charge", Normal, ["Bristleback", "Fanghorn"]),
            new("Bitter crew", Normal, ["Clamberjaw", "Fanghorn"]),
            new("Dark circle", Normal, ["Tremortusk", "Charger"]),
            new("Wide wing", Normal, ["Glinthawk", "Dreadwing", "Spikesnout"]),
            new("Far wedge", Normal, ["Tracker Burrower", "Tracker Burrower"]),
            new("Short spear", Normal, ["Fanghorn", "Glinthawk", "Longleg", "Scrapper"]),
            new("Wide host", Normal, ["Widemaw"]),
            new("Swift crew", Normal, ["Dreadwing", "Sunwing", "Skydrifter"]),
            new("Hot haul", Normal, ["Waterwing", "Widemaw", "Snapmaw"]),
            new("Proud crew", Normal, ["Tracker Burrower", "Bilegut", "Tracker Burrower"]),
            new("Loud volley", Normal, ["Scrapper", "Ravager"]),
            new("Heavy flame", Normal, ["Elemental Clawstrider", "Elemental Clawstrider", "Leaplasher"]),
            new("Bright fist", Normal, ["Thunderjaw", "Scrounger"]),
            new("Steady bleed", Normal, ["Bristleback", "Bellowback"]),
            new("Quiet charge", Normal, ["Plowhorn", "Lancehorn"]),
            new("Low edge", Normal, ["Rollerback", "Spikesnout"]),
            new("Hot band", Normal, ["Tremortusk", "Longleg", "Sunwing"]),
            new("New rush", Normal, ["Charger", "Charger", "Charger", "Charger"]),
            new("Last crew", Normal, ["Bellowback", "Scrapper", "Ravager"]),
            new("Wide edge", Normal, ["Spikesnout", "Spikesnout", "Spikesnout", "Leaplasher"]),
            new("Far anvil", Normal, ["Shellsnapper"]),
            new("First arc", Normal, ["Ravager"]),
            new("Short band", Normal, ["Bellowback", "Scrounger"]),
            new("Short penny", Normal, ["Glinthawk", "Fanghorn", "Longleg"]),
            new("Proud watch", Normal, ["Fanghorn", "Clawstrider", "Clawstrider"]),
            new("Short measure", Normal, ["Sunwing"]),
            new("Long chain", Normal, ["Clawstrider", "Clamberjaw", "Spikesnout"]),
            new("Thin penny", Normal, ["Skydrifter", "Longleg"]),
            new("Tame wing", Normal, ["Sunwing", "Skydrifter", "Scrounger"]),
            new("Tame front", Normal, ["Longleg", "Ravager", "Bellowback"]),
            new("Wary troop", Normal, ["Widemaw", "Snapmaw", "Fanghorn"]),
            new("Cold front", Normal, ["Tremortusk", "Charger"]),
            new("Even guard", Normal, ["Elemental Clawstrider", "Leaplasher"]),
            new("Stout pack", Normal, ["Fireclaw"]),
            new("Blunt guard", Normal, ["Behemoth", "Shell-Walker"]),
            new("Grim chain", Normal, ["Skydrifter", "Glinthawk", "Glinthawk"]),
            new("Rough rush", Normal, ["Charger", "Charger", "Scrounger"]),
            new("Wide circle", Normal, ["Clawstrider", "Clamberjaw"]),
            new("Short charge", Normal, ["Plowhorn", "Bristleback", "Plowhorn", "Lancehorn", "Lancehorn"]),
            new("Heavy circle", Normal, ["Bilegut", "Tracker Burrower"]),
            new("Iron pack", Normal, ["Scrounger", "Leaplasher", "Spikesnout"]),
            new("Wide cohort", Normal, ["Plowhorn", "Lancehorn", "Bristleback", "Lancehorn"]),
            new("Wary wing", Normal, ["Sunwing", "Dreadwing", "Leaplasher"]),
            new("Bright wave", Normal, ["Snapmaw"]),
            new("High guard", Normal, ["Behemoth", "Shell-Walker"]),
            new("Low flight", Normal, ["Plowhorn", "Fanghorn", "Lancehorn"]),
            new("Bold fist", Normal, ["Shellsnapper"]),
            new("Deep bleed", Normal, ["Bristleback", "Bellowback", "Bristleback"]),
            new("First band", Normal, ["Glinthawk", "Sunwing", "Spikesnout"]),
            new("High pack", Normal, ["Bristleback", "Bristleback", "Bristleback"]),
            new("Blunt troop", Normal, ["Lancehorn", "Plowhorn", "Plowhorn"]),
            new("Quiet circle", Normal, ["Waterwing"]),
            new("Bold front", Normal, ["Clawstrider"]),
            new("Lean squad", Fun,
                ["Bellowback", "Bellowback", "Bristleback", "Bellowback", "Bristleback", "Bristleback"]),
            new("Still chain", Fun,
                ["Shell-Walker", "Shell-Walker", "Shell-Walker", "Shell-Walker", "Fanghorn", "Skydrifter"]),
            new("Deep crew", Fun, ["Waterwing", "Tremortusk", "Scrapper"]),
            new("Stout haul", Fun, ["Shellsnapper", "Widemaw", "Widemaw", "Widemaw", "Longleg"]),
            new("Wide crew", Fun,
                ["Snapmaw", "Shellsnapper", "Waterwing", "Tremortusk", "Scrapper", "Fanghorn"]),
            new("Heavy band", Fun, ["Dreadwing", "Tremortusk", "Stalker", "Rollerback", "Longleg"]),
            new("Stout volley", Fun,
                ["Elemental Clawstrider", "Scrapper", "Elemental Clawstrider", "Redeye Watcher"]),
            new("Stout delve", Fun,
                ["Bilegut", "Rockbreaker", "Tracker Burrower", "Tracker Burrower", "Scrapper"]),
            new("Cold muddle", Fun, ["Waterwing", "Dreadwing", "Dreadwing"]),
            new("Long crew", Fun, ["Lancehorn", "Fanghorn", "Fanghorn", "Fanghorn", "Grazer", "Plowhorn"]),
            new("Quiet rush", Fun, ["Charger", "Tremortusk", "Thunderjaw", "Charger", "Spikesnout"]),
            new("Wary band", Fun, ["Shellsnapper", "Clamberjaw", "Longleg"]),
            new("Wary wedge", Fun, ["Clamberjaw", "Clamberjaw", "Clamberjaw", "Clamberjaw", "Skydrifter"]),
            new("Thin spear", Fun, ["Snapmaw", "Waterwing", "Widemaw", "Shellsnapper", "Glinthawk"]),
            new("Dark wing", Fun,
                ["Sunwing", "Glinthawk", "Skydrifter", "Glinthawk", "Dreadwing", "Skydrifter", "Leaplasher"]),
            new("Keen troop", Fun,
                ["Clawstrider", "Clawstrider", "Stalker", "Clawstrider", "Stalker", "Scrapper", "Longleg"]),
            new("Blunt band", Fun, ["Snapmaw", "Ravager", "Sunwing", "Ravager"]),
            new("Iron wing", Fun, ["Dreadwing", "Sunwing", "Glinthawk", "Sunwing", "Glinthawk"]),
            new("High circle", Fun, ["Elemental Clawstrider", "Elemental Clawstrider", "Ravager"]),
            new("Steady band", Fun, ["Rollerback", "Bilegut", "Waterwing", "Scrapper"]),
            new("High squad", Fun, ["Dreadwing", "Waterwing", "Dreadwing", "Skydrifter"]),
            new("Bitter edge", Fun, ["Rollerback", "Rollerback", "Stalker", "Clawstrider", "Scrounger"]),
            new("Wide arc", Fun, ["Tremortusk", "Stormbird"]),
            new("Bright band", Fun,
                ["Elemental Clawstrider", "Scorcher", "Elemental Clawstrider", "Spikesnout", "Scrounger"]),
            new("Thin flight", Fun,
                ["Behemoth", "Shell-Walker", "Behemoth", "Behemoth", "Leaplasher", "Scrounger"]),
            new("Sly wing", Fun, ["Glinthawk", "Stormbird", "Dreadwing", "Skydrifter"]),
            new("Odd column", Fun, ["Tremortusk", "Thunderjaw", "Tremortusk", "Leaplasher"]),
            new("Grim crew", Fun, ["Lancehorn", "Scrounger", "Fanghorn", "Longleg", "Scrapper", "Longleg"]),
            new("Wary volley", Fun,
                ["Ravager", "Bellowback", "Redeye Watcher", "Redeye Watcher", "Spikesnout", "Scrapper"]),
            new("Swift charge", Fun,
                ["Plowhorn", "Lancehorn", "Fanghorn", "Grazer", "Lancehorn", "Plowhorn"]),
            new("Loud wedge", Fun,
                ["Longleg", "Redeye Watcher", "Ravager", "Bellowback", "Ravager", "Charger", "Spikesnout"]),
            new("Iron delve", Fun, ["Slitherfang", "Rockbreaker"]),
            new("Light flight", Fun,
                ["Slaughterspine", "Bellowback", "Bristleback", "Bristleback", "Scrounger"]),
            new("Loud shadow", Fun, ["Clamberjaw", "Clamberjaw", "Stalker", "Burrower"]),
            new("Low delve", Fun,
                ["Rockbreaker", "Bilegut", "Tracker Burrower", "Tracker Burrower", "Leaplasher", "Tracker Burrower"]),
            new("Wide guard", Fun, ["Shell-Walker", "Behemoth", "Shell-Walker", "Shell-Walker", "Behemoth"]),
            new("Lean wing", Fun, ["Sunwing", "Skydrifter", "Stormbird", "Sunwing", "Spikesnout", "Grazer"]),
            new("Deep band", Fun, ["Widemaw", "Widemaw", "Snapmaw", "Widemaw"]),
            new("Odd troop", Fun, ["Scorcher", "Scorcher", "Glinthawk"]),
            new("Lean guard", Fun, ["Behemoth", "Behemoth", "Shell-Walker", "Burrower", "Grazer"]),
            new("Even wedge", Fun, ["Bilegut", "Rollerback", "Rollerback", "Waterwing", "Scrounger"]),
            new("Steady edge", Fun, ["Clawstrider", "Rollerback", "Stalker"]),
            new("Bitter bleed", Fun,
                ["Bristleback", "Bristleback", "Bellowback", "Bellowback", "Bristleback", "Bristleback"]),
            new("Sly crew", Fun,
                ["Dreadwing", "Dreadwing", "Waterwing", "Waterwing", "Fanghorn", "Leaplasher"]),
            new("First column", Fun, ["Behemoth", "Behemoth", "Skydrifter"]),
            new("Tame measure", Fun, ["Clawstrider", "Tremortusk", "Widemaw", "Widemaw"]),
            new("Wild guard", Fun, ["Behemoth", "Shell-Walker", "Behemoth", "Shell-Walker", "Longleg"]),
            new("Low watch", Fun, ["Ravager", "Ravager", "Tremortusk", "Spikesnout"]),
            new("Blunt charge", Fun,
                ["Lancehorn", "Fanghorn", "Plowhorn", "Fanghorn", "Grazer", "Charger", "Longleg"]),
            new("Bold guard", Fun, ["Behemoth", "Shell-Walker", "Shell-Walker", "Behemoth"]),
            new("Old rush", Fun, ["Thunderjaw", "Slitherfang", "Charger"]),
            new("Far host", Fun, ["Snapmaw", "Stalker", "Bilegut", "Snapmaw", "Skydrifter"]),
            new("Short claw", Fun,
                ["Apex Clawstrider", "Apex Clawstrider", "Clawstrider", "Rollerback", "Leaplasher", "Spikesnout"]),
            new("Stout wave", Fun, ["Bilegut", "Bilegut", "Bilegut"]),
            new("Loud host", Fun, ["Clamberjaw", "Clamberjaw", "Sunwing"]),
            new("Wary delve", Fun, ["Bilegut", "Slitherfang", "Tracker Burrower", "Tracker Burrower"]),
            new("Lean troop", Fun, ["Tideripper", "Shellsnapper", "Scrounger", "Burrower"]),
            new("Stout troop", Fun,
                ["Elemental Clawstrider", "Elemental Clawstrider", "Scorcher", "Elemental Clawstrider", "Grazer", "Burrower"]),
            new("Cold shadow", Fun, ["Stalker", "Stalker", "Clamberjaw"]),
            new("Cold charge", Fun,
                ["Plowhorn", "Fanghorn", "Lancehorn", "Grazer", "Lancehorn", "Plowhorn", "Plowhorn"]),
            new("Swift flame", Fun, ["Fireclaw", "Elemental Clawstrider"]),
            new("Tame muddle", Fun, ["Waterwing", "Waterwing", "Dreadwing"]),
            new("Bright anvil", Fun, ["Shellsnapper", "Snapmaw", "Glinthawk"]),
            new("Even volley", Fun, ["Redeye Watcher", "Redeye Watcher", "Ravager", "Redeye Watcher"]),
            new("Short cohort", Fun, ["Snapmaw", "Widemaw", "Tideripper", "Snapmaw"]),
            new("Bright claw", Fun,
                ["Clamberjaw", "Clamberjaw", "Clamberjaw", "Clamberjaw", "Skydrifter", "Scrapper"]),
            new("Thin anvil", Mad, ["Stormbird", "Shellsnapper", "Tideripper", "Scrapper"]),
            new("Steady muddle", Mad,
                ["Waterwing", "Dreadwing", "Dreadwing", "Dreadwing", "Scrounger", "Burrower"]),
            new("Keen guard", Mad,
                ["Shell-Walker", "Behemoth", "Shell-Walker", "Behemoth", "Behemoth", "Behemoth", "Scrapper", "Longleg"]),
            new("Far rush", Mad, ["Charger", "Thunderjaw", "Slitherfang", "Charger", "Glinthawk"]),
            new("Bold chain", Mad,
                ["Redeye Watcher", "Rockbreaker", "Ravager", "Scrapper", "Ravager", "Glinthawk", "Skydrifter"]),
            new("Bitter muddle", Mad, ["Dreadwing", "Dreadwing", "Dreadwing", "Waterwing", "Scrounger"]),
            new("Grim muddle", Mad, ["Dreadwing", "Dreadwing", "Waterwing", "Dreadwing", "Leaplasher"]),
            new("Sly line", Mad,
                ["Widemaw", "Snapmaw", "Widemaw", "Snapmaw", "Widemaw", "Snapmaw", "Longleg", "Spikesnout", "Leaplasher"]),
            new("Keen haul", Mad, ["Shellsnapper", "Shellsnapper", "Shellsnapper", "Bilegut", "Charger"]),
            new("High wedge", Mad,
                ["Bellowback", "Elemental Clawstrider", "Redeye Watcher", "Longleg", "Scrapper", "Elemental Clawstrider", "Leaplasher", "Grazer"]),
            new("Grim column", Mad,
                ["Skydrifter", "Sunwing", "Stormbird", "Stormbird", "Lancehorn", "Tracker Burrower"]),
            new("Cold line", Mad,
                ["Clawstrider", "Clawstrider", "Stalker", "Fireclaw", "Clawstrider", "Rollerback", "Fanghorn", "Tracker Burrower"]),
            new("Lean cohort", Mad,
                ["Thunderjaw", "Ravager", "Tremortusk", "Stormbird", "Thunderjaw", "Glinthawk", "Spikesnout"]),
            new("Loud guard", Mad,
                ["Shellsnapper", "Shellsnapper", "Fireclaw", "Rockbreaker", "Shellsnapper", "Burrower", "Scrounger"]),
            new("Last host", Mad,
                ["Shell-Walker", "Shell-Walker", "Shell-Walker", "Behemoth", "Shell-Walker", "Scrounger", "Plowhorn"]),
            new("Blunt spear", Mad,
                ["Stormbird", "Thunderjaw", "Ravager", "Thunderjaw", "Skydrifter", "Fanghorn"]),
            new("Sly measure", Mad,
                ["Rollerback", "Sunwing", "Rollerback", "Apex Clawstrider", "Lancehorn", "Tracker Burrower"]),
            new("Tame column", Mad,
                ["Rollerback", "Clawstrider", "Clawstrider", "Stalker", "Stalker", "Grazer", "Burrower"]),
            new("Hot wave", Mad,
                ["Tremortusk", "Apex Clawstrider", "Apex Clawstrider", "Sunwing", "Longleg"]),
            new("Iron arc", Mad, ["Ravager", "Stormbird", "Thunderjaw", "Stormbird", "Leaplasher"]),
            new("Light spear", Mad,
                ["Tremortusk", "Slitherfang", "Scorcher", "Tremortusk", "Charger", "Scrapper", "Spikesnout"]),
            new("First edge", Mad,
                ["Rollerback", "Apex Clawstrider", "Apex Clawstrider", "Fireclaw", "Rollerback", "Fanghorn", "Spikesnout"]),
            new("Stout arc", Mad, ["Stormbird", "Ravager", "Ravager", "Thunderjaw", "Longleg"]),
            new("Old shadow", Mad,
                ["Clamberjaw", "Clamberjaw", "Clamberjaw", "Clamberjaw", "Stalker", "Leaplasher", "Glinthawk"]),
            new("Keen rush", Mad,
                ["Slitherfang", "Tremortusk", "Scorcher", "Charger", "Grazer", "Glinthawk"]),
            new("Lean watch", Mad,
                ["Widemaw", "Bilegut", "Snapmaw", "Tideripper", "Skydrifter", "Tracker Burrower"]),
            new("Sharp chain", Mad, ["Shellsnapper", "Tideripper", "Shellsnapper", "Scrapper"]),
            new("Proud host", Mad,
                ["Sunwing", "Elemental Clawstrider", "Tremortusk", "Snapmaw", "Redeye Watcher", "Lancehorn", "Plowhorn"]),
            new("Sharp delve", Mad, ["Rockbreaker", "Slitherfang", "Rockbreaker", "Burrower"]),
            new("Dark watch", Mad,
                ["Shell-Walker", "Shell-Walker", "Behemoth", "Shell-Walker", "Shell-Walker", "Shell-Walker", "Scrounger", "Leaplasher"]),
            new("Thin flame", Mad,
                ["Elemental Clawstrider", "Elemental Clawstrider", "Scorcher", "Fireclaw", "Burrower"]),
            new("Short shadow", Mad,
                ["Stalker", "Clamberjaw", "Clamberjaw", "Clamberjaw", "Skydrifter", "Scrapper"]),
            new("Low anvil", Mad,
                ["Tideripper", "Frostclaw", "Shellsnapper", "Rockbreaker", "Plowhorn", "Longleg"]),
            new("Hot column", Mad,
                ["Waterwing", "Waterwing", "Dreadwing", "Waterwing", "Dreadwing", "Waterwing", "Grazer", "Charger"]),
            new("Short squad", Mad, ["Behemoth", "Behemoth", "Behemoth", "Shell-Walker", "Tracker Burrower"]),
            new("Wide squad", Mad, ["Fireclaw", "Scorcher", "Frostclaw", "Tideripper", "Spikesnout"]),
            new("Even column", Mad,
                ["Bellowback", "Bellowback", "Slaughterspine", "Slaughterspine", "Fanghorn", "Glinthawk"]),
            new("Tame anvil", Mad, ["Slitherfang", "Rockbreaker", "Tideripper", "Scrounger"]),
            new("Even chain", Mad, ["Waterwing", "Dreadwing", "Dreadwing", "Dreadwing", "Glinthawk"]),
            new("Sly watch", Mad,
                ["Tracker Burrower", "Rockbreaker", "Bilegut", "Rockbreaker", "Skydrifter", "Fanghorn"]),
            new("Proud front", Mad,
                ["Shell-Walker", "Behemoth", "Behemoth", "Shell-Walker", "Behemoth", "Burrower", "Scrounger"]),
            new("Sly troop", Mad, ["Shell-Walker", "Behemoth", "Behemoth", "Behemoth", "Lancehorn"]),
            new("Odd pack", Mad,
                ["Tremortusk", "Thunderjaw", "Stormbird", "Tremortusk", "Plowhorn", "Grazer"]),
            new("First measure", Mad,
                ["Redeye Watcher", "Widemaw", "Clawstrider", "Snapmaw", "Rollerback", "Sunwing", "Charger", "Scrapper"]),
            new("Deep anvil", Mad, ["Shellsnapper", "Frostclaw", "Fireclaw", "Spikesnout"]),
            new("Iron edge", Mad,
                ["Apex Clawstrider", "Stalker", "Apex Clawstrider", "Rollerback", "Lancehorn"]),
            new("Blunt anvil", Outlandish,
                ["Tideripper", "Scorcher", "Slitherfang", "Shellsnapper", "Tideripper", "Fireclaw", "Leaplasher", "Longleg", "Grazer"]),
            new("Odd bleed", Outlandish,
                ["Slaughterspine", "Bellowback", "Slaughterspine", "Bellowback", "Bristleback", "Slaughterspine", "Scrounger", "Skydrifter"]),
            new("Lean flame", Outlandish,
                ["Elemental Clawstrider", "Fireclaw", "Fireclaw", "Elemental Clawstrider", "Scorcher", "Fireclaw", "Leaplasher", "Longleg"]),
            new("Dark rush", Outlandish,
                ["Charger", "Slitherfang", "Scorcher", "Tremortusk", "Charger", "Slitherfang", "Tracker Burrower", "Glinthawk"]),
            new("Bold watch", Outlandish,
                ["Frostclaw", "Tideripper", "Shellsnapper", "Stormbird", "Tideripper", "Thunderjaw", "Lancehorn", "Scrapper", "Spikesnout"]),
            new("Steady spear", Outlandish,
                ["Bellowback", "Slaughterspine", "Bellowback", "Bristleback", "Slaughterspine", "Slaughterspine", "Burrower", "Fanghorn", "Skydrifter"]),
            new("Wild pack", Outlandish,
                ["Tremortusk", "Thunderjaw", "Stormbird", "Tremortusk", "Tremortusk", "Tremortusk", "Scrapper", "Lancehorn", "Plowhorn"]),
            new("Still front", Outlandish,
                ["Frostclaw", "Shellsnapper", "Rockbreaker", "Rockbreaker", "Slitherfang", "Shellsnapper", "Tracker Burrower", "Scrounger", "Glinthawk"]),
            new("Bold circle", Outlandish,
                ["Scorcher", "Fireclaw", "Elemental Clawstrider", "Fireclaw", "Elemental Clawstrider", "Scorcher", "Plowhorn", "Leaplasher", "Longleg"]),
            new("Rough circle", Outlandish,
                ["Slitherfang", "Charger", "Slitherfang", "Charger", "Thunderjaw", "Scorcher", "Fanghorn", "Spikesnout", "Scrounger"]),
            new("Old watch", Outlandish,
                ["Charger", "Scorcher", "Thunderjaw", "Tremortusk", "Tremortusk", "Slitherfang", "Longleg", "Burrower"]),
            new("Last anvil", Outlandish,
                ["Frostclaw", "Stormbird", "Rockbreaker", "Frostclaw", "Shellsnapper", "Shellsnapper", "Glinthawk", "Fanghorn"]),
            new("Steady line", Outlandish,
                ["Fireclaw", "Fireclaw", "Fireclaw", "Elemental Clawstrider", "Scorcher", "Scorcher", "Leaplasher", "Grazer"]),
            new("Iron fist", Outlandish,
                ["Rockbreaker", "Rockbreaker", "Bilegut", "Bilegut", "Slitherfang", "Rockbreaker", "Tracker Burrower", "Scrapper", "Grazer"]),
            new("Cold column", Outlandish,
                ["Tideripper", "Tideripper", "Stormbird", "Frostclaw", "Tideripper", "Stormbird", "Burrower", "Bristleback"]),
            new("High anvil", Outlandish,
                ["Frostclaw", "Shellsnapper", "Tideripper", "Tideripper", "Thunderjaw", "Stormbird", "Spikesnout", "Plowhorn"]),
            new("Keen flame", Outlandish,
                ["Elemental Clawstrider", "Elemental Clawstrider", "Scorcher", "Elemental Clawstrider", "Elemental Clawstrider", "Scorcher", "Scrapper", "Lancehorn", "Lancehorn"]),
            new("Quiet claw", Outlandish,
                ["Thunderjaw", "Thunderjaw", "Tremortusk", "Slitherfang", "Charger", "Tremortusk", "Skydrifter", "Scrounger", "Plowhorn"]),
            new("Bold delve", Outlandish,
                ["Tracker Burrower", "Bilegut", "Rockbreaker", "Bilegut", "Rockbreaker", "Slitherfang", "Burrower", "Fanghorn", "Glinthawk"]),
            new("Wide anvil", Outlandish,
                ["Shellsnapper", "Stormbird", "Tideripper", "Slaughterspine", "Shellsnapper", "Slaughterspine", "Longleg", "Bristleback", "Skydrifter"]),
            new("New column", Outlandish,
                ["Fireclaw", "Slaughterspine", "Stormbird", "Tideripper", "Thunderjaw", "Frostclaw", "Grazer", "Longleg"]),
            new("Long anvil", Outlandish,
                ["Rockbreaker", "Frostclaw", "Frostclaw", "Slaughterspine", "Slitherfang", "Shellsnapper", "Plowhorn", "Spikesnout", "Burrower"]),
            new("Cold anvil", Outlandish,
                ["Stormbird", "Frostclaw", "Fireclaw", "Tideripper", "Scorcher", "Thunderjaw", "Leaplasher", "Scrounger"]),
            new("Wild delve", Outlandish,
                ["Tracker Burrower", "Slitherfang", "Rockbreaker", "Rockbreaker", "Slitherfang", "Bilegut", "Lancehorn", "Glinthawk", "Leaplasher"]),
            new("Bitter wave", Outlandish,
                ["Bellowback", "Slaughterspine", "Bristleback", "Bellowback", "Slaughterspine", "Slaughterspine", "Scrapper", "Grazer"]),
            new("Wild flight", Outlandish,
                ["Fireclaw", "Scorcher", "Fireclaw", "Fireclaw", "Scorcher", "Skydrifter", "Spikesnout"]),
            new("Short delve", Outlandish,
                ["Rockbreaker", "Slitherfang", "Bilegut", "Rockbreaker", "Tracker Burrower", "Slitherfang", "Skydrifter", "Bristleback"]),
            new("Bold flame", Outlandish,
                ["Fireclaw", "Elemental Clawstrider", "Scorcher", "Elemental Clawstrider", "Scorcher", "Elemental Clawstrider", "Fanghorn", "Longleg", "Burrower"]),
            new("Hot guard", Outlandish,
                ["Fireclaw", "Fireclaw", "Scorcher", "Fireclaw", "Elemental Clawstrider", "Fireclaw", "Leaplasher", "Scrapper", "Fanghorn"]),
            new("Bitter flame", Outlandish,
                ["Scorcher", "Fireclaw", "Fireclaw", "Elemental Clawstrider", "Scorcher", "Fireclaw", "Spikesnout", "Glinthawk"]),
            new("Grim flame", Outlandish,
                ["Scorcher", "Elemental Clawstrider", "Scorcher", "Fireclaw", "Elemental Clawstrider", "Fireclaw", "Scrounger", "Plowhorn", "Grazer"]),
            new("Even bleed", Outlandish,
                ["Slaughterspine", "Slaughterspine", "Bristleback", "Bellowback", "Slaughterspine", "Lancehorn", "Scrapper"]),
            new("Still flame", Outlandish,
                ["Elemental Clawstrider", "Fireclaw", "Scorcher", "Elemental Clawstrider", "Fireclaw", "Fireclaw", "Lancehorn", "Burrower"]),
            new("Dark wave", Outlandish,
                ["Slaughterspine", "Bristleback", "Slaughterspine", "Slaughterspine", "Bristleback", "Bristleback", "Glinthawk", "Scrounger"]),
            new("Even flame", Outlandish,
                ["Scorcher", "Fireclaw", "Scorcher", "Fireclaw", "Fireclaw", "Scorcher", "Plowhorn", "Longleg"]),
            new("Sly claw", Outlandish,
                ["Scorcher", "Elemental Clawstrider", "Elemental Clawstrider", "Fireclaw", "Fireclaw", "Elemental Clawstrider", "Grazer", "Leaplasher", "Fanghorn"]),
            new("Heavy bleed", Outlandish,
                ["Slaughterspine", "Bellowback", "Bristleback", "Slaughterspine", "Bristleback", "Slaughterspine", "Tracker Burrower", "Skydrifter", "Charger"]),
            new("Tame flame", Outlandish,
                ["Scorcher", "Fireclaw", "Fireclaw", "Scorcher", "Scorcher", "Scorcher", "Skydrifter", "Spikesnout"]),
            new("Still circle", Outlandish,
                ["Bilegut", "Bilegut", "Tracker Burrower", "Slitherfang", "Rockbreaker", "Slitherfang", "Fanghorn", "Longleg"]),
            new("Long host", Outlandish,
                ["Frostclaw", "Shellsnapper", "Shellsnapper", "Tideripper", "Shellsnapper", "Stormbird", "Lancehorn", "Scrapper", "Spikesnout"]),
            new("Nine spines", Insane,
                ["Slaughterspine", "Slaughterspine", "Slaughterspine", "Slaughterspine", "Slaughterspine", "Slaughterspine", "Slaughterspine", "Slaughterspine", "Slaughterspine"]),
            new("Nine fangs", Insane,
                ["Slitherfang", "Slitherfang", "Slitherfang", "Slitherfang", "Slitherfang", "Slitherfang", "Slitherfang", "Slitherfang", "Slitherfang"]),
            new("Nine scorchers", Insane,
                ["Scorcher", "Scorcher", "Scorcher", "Scorcher", "Scorcher", "Scorcher", "Scorcher", "Scorcher", "Scorcher"]),
            new("One spine", Insane, ["Slaughterspine"]),
            new("One burrower", Insane, ["Burrower"]),
            new("Nine burrowers", Insane,
                ["Burrower", "Burrower", "Burrower", "Burrower", "Burrower", "Burrower", "Burrower", "Burrower", "Burrower"]),
            new("Nine grazers", Insane,
                ["Grazer", "Grazer", "Grazer", "Grazer", "Grazer", "Grazer", "Grazer", "Grazer", "Grazer"]),
            new("Thunder wall", Insane,
                ["Thunderjaw", "Thunderjaw", "Thunderjaw", "Thunderjaw", "Thunderjaw", "Thunderjaw", "Thunderjaw", "Thunderjaw", "Thunderjaw"]),
            new("Frost wall", Insane,
                ["Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw"]),
            new("Fire wall", Insane,
                ["Fireclaw", "Fireclaw", "Fireclaw", "Fireclaw", "Fireclaw", "Fireclaw", "Fireclaw", "Fireclaw", "Fireclaw"]),
            new("Tide wall", Insane,
                ["Tideripper", "Tideripper", "Tideripper", "Tideripper", "Tideripper", "Tideripper", "Tideripper", "Tideripper", "Tideripper"]),
            new("Storm wall", Insane,
                ["Stormbird", "Stormbird", "Stormbird", "Stormbird", "Stormbird", "Stormbird", "Stormbird", "Stormbird", "Stormbird"]),
            new("Behemoth wall", Insane,
                ["Behemoth", "Behemoth", "Behemoth", "Behemoth", "Behemoth", "Behemoth", "Behemoth", "Behemoth", "Behemoth"]),
            new("Rock wall", Insane,
                ["Rockbreaker", "Rockbreaker", "Rockbreaker", "Rockbreaker", "Rockbreaker", "Rockbreaker", "Rockbreaker", "Rockbreaker", "Rockbreaker"]),
            new("Apex wall", Insane,
                ["Apex Clawstrider", "Apex Clawstrider", "Apex Clawstrider", "Apex Clawstrider", "Apex Clawstrider", "Apex Clawstrider", "Apex Clawstrider", "Apex Clawstrider", "Apex Clawstrider"]),
            new("Two spines", Insane, ["Slaughterspine", "Slaughterspine"]),
            new("Spine and fang", Insane, ["Slaughterspine", "Slitherfang"]),
            new("Every elemental", Insane,
                ["Fireclaw", "Frostclaw", "Scorcher", "Elemental Clawstrider", "Bellowback", "Bilegut"]),
            new("The whole sky", Insane,
                ["Stormbird", "Dreadwing", "Sunwing", "Skydrifter", "Glinthawk", "Waterwing", "Stormbird", "Dreadwing", "Sunwing"]),
            new("Ten pounds", Insane, ["Slaughterspine"]),
            new("Penny army", Insane,
                ["Burrower", "Grazer", "Leaplasher", "Scrounger", "Spikesnout", "Burrower", "Grazer", "Leaplasher", "Scrounger"]),
            new("Top and bottom", Insane, ["Slaughterspine", "Burrower"]),
            new("Costly nine", Insane,
                ["Slaughterspine", "Slitherfang", "Scorcher", "Fireclaw", "Frostclaw", "Thunderjaw", "Stormbird", "Tideripper", "Rockbreaker"]),
            new("All the haulers", Insane,
                ["Tideripper", "Shellsnapper", "Bilegut", "Waterwing", "Snapmaw", "Widemaw", "Tideripper", "Shellsnapper", "Bilegut"]),
            new("Unearth nine", Insane,
                ["Slitherfang", "Rockbreaker", "Bilegut", "Tracker Burrower", "Slitherfang", "Rockbreaker", "Bilegut", "Tracker Burrower", "Slitherfang"]),
            new("Blind nine", Insane,
                ["Redeye Watcher", "Redeye Watcher", "Redeye Watcher", "Redeye Watcher", "Redeye Watcher", "Redeye Watcher", "Redeye Watcher", "Redeye Watcher", "Redeye Watcher"]),
            new("Shield nine", Insane,
                ["Shell-Walker", "Shell-Walker", "Shell-Walker", "Shell-Walker", "Shell-Walker", "Shell-Walker", "Shell-Walker", "Shell-Walker", "Shell-Walker"]),
            new("Retaliation", Insane,
                ["Rollerback", "Apex Clawstrider", "Rollerback", "Apex Clawstrider", "Rollerback", "Apex Clawstrider", "Rollerback", "Apex Clawstrider", "Rollerback"]),
            new("Stalk nine", Insane,
                ["Stalker", "Clamberjaw", "Stalker", "Clamberjaw", "Stalker", "Clamberjaw", "Stalker", "Clamberjaw", "Stalker"]),
            new("Spill nine", Insane,
                ["Slaughterspine", "Bellowback", "Bristleback", "Slaughterspine", "Bellowback", "Bristleback", "Slaughterspine", "Bellowback", "Bristleback"]),
            new("Confuse pair", Insane, ["Waterwing", "Dreadwing"]),
            new("Freeze nine", Insane,
                ["Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw", "Frostclaw"]),
            new("Burn nine", Insane,
                ["Fireclaw", "Scorcher", "Elemental Clawstrider", "Fireclaw", "Scorcher", "Elemental Clawstrider", "Fireclaw", "Scorcher", "Elemental Clawstrider"]),
            new("Slowest nine", Insane,
                ["Slaughterspine", "Behemoth", "Tremortusk", "Shellsnapper", "Tideripper", "Widemaw", "Snapmaw", "Shell-Walker", "Clawstrider"]),
        ];
    }
}
